// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockView.Data;

namespace StockView.Migrations
{
    [DbContext(typeof(StockviewDataContext))]
    [Migration("20221106002839_AlterStockviewDC")]
    partial class AlterStockviewDC
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StockView.Models.Stocks", b =>
                {
                    b.Property<string>("Ticker")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AverageVolume")
                        .HasColumnType("int");

                    b.Property<decimal>("DayClose")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<decimal>("DayOpen")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<string>("Exchange")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("MarketCap")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Volume")
                        .HasColumnType("int");

                    b.Property<decimal>("YearlyHigh")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<decimal>("YearlyLow")
                        .HasColumnType("decimal(6, 2)");

                    b.HasKey("Ticker");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("StockView.Models.Watchlist", b =>
                {
                    b.Property<int>("WatchlistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GenericUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WatchlistName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WatchlistId");

                    b.ToTable("watchlist");
                });
#pragma warning restore 612, 618
        }
    }
}
